replicaCount: 1

image:
  repository: chewiclinton/feedback-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8009

resources:
  requests:
    memory: "96Mi"
    cpu: "75m"
  limits:
    memory: "192Mi"
    cpu: "200m"

config:
  DB_HOST: postgres-feedback-svc
  DB_PORT: "5432"
  DB_NAME: lexcam_feedback
  DB_USER: lexcam
  RABBITMQ_URL: amqp://lexcam:lexcam_dev@rabbitmq-svc:5672/
  USER_MANAGEMENT_URL: http://user-management-svc:8001

secrets:
  DATABASE_URL: "postgresql://lexcam:lexcam_dev@postgres-feedback-svc:5432/lexcam_feedback"
  DB_PASSWORD: "lexcam_dev"
  SECRET_KEY: "change-me-in-production"

hpa:
  enabled: false
