replicaCount: 1

image:
  repository: chewiclinton/frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

config:
  USER_MANAGEMENT_URL: "http://kong-proxy-svc:80"
  LAWYER_SERVICE_URL: "http://kong-proxy-svc:80"
  KNOWLEDGE_BASE_URL: "http://kong-proxy-svc:80"
  RAG_SERVICE_URL: "http://kong-proxy-svc:80"
  DOCUMENT_SERVICE_URL: "http://kong-proxy-svc:80"
  PAYMENT_SERVICE_URL: "http://kong-proxy-svc:80"
  FEEDBACK_SERVICE_URL: "http://kong-proxy-svc:80"
  SCRAPER_SERVICE_URL: "http://kong-proxy-svc:80"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
