image:
  repository: chewiclinton/indexing-worker
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"

config:
  KB_SERVICE_URL: http://knowledge-base-service-svc:8003
  EMBEDDING_SERVICE_URL: http://embedding-service:8000
  RABBITMQ_URL: amqp://lexcam:lexcam_dev@rabbitmq-svc:5672/
  QDRANT_URL: http://qdrant-svc:6333
  QDRANT_COLLECTION: lexcam_laws
  CHUNK_SIZE: "500"
  CHUNK_OVERLAP: "50"

secrets:
  INTERNAL_SERVICE_KEY: "dev-internal-key"
