# Generated by Django 4.2.16 on 2026-05-12 12:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lawyer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(blank=True, null=True, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=100)),
                ("region", models.CharField(blank=True, default="", max_length=100)),
                ("bio", models.TextField(blank=True, null=True)),
                ("profile_photo_url", models.URLField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("registered", "Registered"), ("scraped", "Scraped")],
                        default="registered",
                        max_length=20,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_listed", models.BooleanField(default=False)),
                ("is_accepting_cases", models.BooleanField(default=True)),
                ("source_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "lawyers",
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("name_fr", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "specializations",
            },
        ),
        migrations.CreateModel(
            name="LawyerSpecialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lawyers.lawyer"
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lawyers.specialization",
                    ),
                ),
            ],
            options={
                "db_table": "lawyer_specializations",
                "unique_together": {("lawyer", "specialization")},
            },
        ),
        migrations.CreateModel(
            name="LawyerDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("bar_certificate", "Bar Certificate"),
                            ("national_id", "National ID"),
                            ("diploma", "Diploma"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file_url", models.URLField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="lawyers.lawyer",
                    ),
                ),
            ],
            options={
                "db_table": "lawyer_documents",
            },
        ),
        migrations.AddField(
            model_name="lawyer",
            name="specializations",
            field=models.ManyToManyField(
                blank=True,
                related_name="lawyers",
                through="lawyers.LawyerSpecialization",
                to="lawyers.specialization",
            ),
        ),
    ]
