apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "document-service.name" . }}
  labels:
    {{- include "document-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "document-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "document-service.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.port }}"
        prometheus.io/path: /metrics
    spec:
      containers:
        - name: document-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "document-service.name" . }}-config
            - secretRef:
                name: {{ include "document-service.name" . }}-secret
          command: ["sh", "-c", "python manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:8006 --workers 2"]
          readinessProbe:
            httpGet:
              path: /api/v1/templates
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/templates
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: document-consumer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "document-service.name" . }}-config
            - secretRef:
                name: {{ include "document-service.name" . }}-secret
          command: ["python", "manage.py", "consume_events"]
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
