apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-management.name" . }}-secret
  labels:
    {{- include "user-management.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
