apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-management.name" . }}-svc
  labels:
    {{- include "user-management.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "user-management.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
