apiVersion: v1
kind: Service
metadata:
  name: {{ include "scraper-service.name" . }}-svc
  labels:
    {{- include "scraper-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "scraper-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
