apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scraper-service.name" . }}-worker
  labels:
    {{- include "scraper-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "scraper-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "scraper-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: scraper-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "scraper-service.name" . }}-config
            - secretRef:
                name: {{ include "scraper-service.name" . }}-secret
          command: ["celery", "-A", "app.tasks.celery_app", "worker", "-l", "info", "-Q", "default"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
