apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lawyer-service.name" . }}-secret
  labels:
    {{- include "lawyer-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
