apiVersion: v1
kind: Service
metadata:
  name: {{ include "lawyer-service.name" . }}-svc
  labels:
    {{- include "lawyer-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "lawyer-service.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
