apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "admin-panel.name" . }}
  labels:
    {{- include "admin-panel.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "admin-panel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "admin-panel.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.port }}"
        prometheus.io/path: /metrics
    spec:
      containers:
        - name: admin-panel
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "admin-panel.name" . }}-config
            - secretRef:
                name: {{ include "admin-panel.name" . }}-secret
          command: ["python", "manage.py", "runserver", "0.0.0.0:8010"]
          readinessProbe:
            httpGet:
              path: /api/v1/schema/
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/schema/
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
