apiVersion: v1
kind: Secret
metadata:
  name: {{ include "admin-panel.name" . }}-secret
  labels:
    {{- include "admin-panel.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
