apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "indexing-worker.name" . }}
  labels:
    {{- include "indexing-worker.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "indexing-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "indexing-worker.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: indexing-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "worker.py"]
          envFrom:
            - configMapRef:
                name: {{ include "indexing-worker.name" . }}-config
            - secretRef:
                name: {{ include "indexing-worker.name" . }}-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
