apiVersion: v1
kind: Secret
metadata:
  name: {{ include "embedding-service.fullname" . }}-secrets
  labels:
    {{- include "embedding-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.secret.API_KEY | quote }}
