apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification-service.name" . }}-secret
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
